language: node_js
node_js:
- 6.9.5
notifications:
  email: false
  webhooks: https://ambrosio-tele.herokuapp.com/sacarinobot/travisci/133188453
  on_success: always
  on_failure: always
  on_start: always
before_script:
- npm install -g grunt-cli
deploy:
  api_key:
    secure: EH+xnBVCsWJx81dyeOjcxWR55/WtWvjnq2mNzyDUMyTw0ZWni2+z5rTE7M4oulXxfdTRsin25WxAfCRxmBOotnH1OL9e1ZPmH3vR4jizhG2SX6SuL7BSTydX7dZgksNcV7oQMXSPYnTrhyj4HWVzRuFooRLpfaAy9jxaUxUj1EF9DLrzBvGoh6Rxkx7IW3hL302KTFRdwYs7b3Ed02Ys2Mrw948HDVIGeOipZf94alPEA70vEyIoRKMCwnpxk0XgPsgPvU9qIQzawLkJ1cy1/l17L9yUKkOs9OknPcF+0zY9XRZ6eKOxK6aBvCIhHx7dQRJxOkZM2JGK5RwKQMRXuGdMSCt+oHlE15ZplQZht4ZfCRswTO3rXA7Fiecc3rW5zx6brsSVUVIh/713lhKTxPKC5Lb/Vw3YLXR5Wrq5hDs9xKocH0ExVf4n7V315m6CUeExPlE+0veVfYOwn13N0bNdSoNAlh/sR7bzUVCDQZda5YR5VDFOFf2WrlTCRbLfGcaXLMkcjWErIwU9ckaWFaND2E2xdpWtmY8mxMQKKgn0fMMfIhwh6xanH8ysPsiO7mY2yjYBvcQg0Fl4xuikL92rmqZw0et0mGoSAjNDOcN4jU0Mi4vg3d4aydL8JkIix0fuooS7TJKRWgFQG9wyxKc6kd0s0j+tdKkzvq85JRU=
  email:
    secure: aoq6qqE7E45GDlnoEHU86YvDJrSgvrmCRLRrkmGs25tj1ZKs11JDH1tGyzZ87XMtloRr3q6k9WzU6BJOyFuWT8sQhu7A59ylWepmzhkOlj4X6xDFpQMC8CiVLCLRaYbFYaMRsNMXHd0BphMnDB36mrIoo3cP1lnRgdymRqjBVAryOThADEYydGO5iNNmR4uFLX1tAHipIGSdViAwTEwQ0ffq1Y5zv7Uh1UCcFN1QbaIlOlrqb2mCLlQnKg0aUt6OKiIbdHDJwjSpVbuHH1QwFzaLf3X2EM8dA4GgyHRwwlTPdZqABv1uQsxS4KEF9isw6+us9PSxBZw9Bevkt2BtffWYEqSWGtY8hwMjSfnrWYwSBoiqKeWpGtNBaPLWn0nn7VnNN5gS0PgJwtcppUvZj6BQV/qSxKJnS3hQgrcy/mGreJuUMjskbWCPjfMRPRfbVYCDW5qi8pn3o5O9Q4cJjNFZPpt6HOQmfffPjT1/kr29yqv3HrtQgmbTo63N9vCiTgVxfbVmn0h4RfLIOZcyf2Rg7qtLBtGO8a00f2u6klXMwr5vILwzOknpApuzEatM6ydHH/MK3cBr09zB1hVIBmfkKSakdfpCHSL+rTCVhSmpKx+uLcCy2fSRVBGIlHSySCGq7UTUffHoGZGJ36m1cEMyriUBrs52mpQ7I+VdHxg=
  provider: npm
